- shell:
        - if [ ! -d "$HOME/.oh-my-zsh" ]; then /bin/sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"; fi;
- link:
        ~/.zshrc: shells/zsh/zshrc
        ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions: shells/zsh/oh-my-zsh/custom/plugins/zsh-autosuggestions
        ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting: shells/zsh/oh-my-zsh/custom/plugins/zsh-syntax-highlighting
